# Generated by Django 6.0.6 on 2026-06-04 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL标签')),
            ],
            options={
                'verbose_name': '陶瓷分类',
                'verbose_name_plural': '陶瓷分类',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='陶瓷名称')),
                ('short_description', models.CharField(help_text='这段文字会显示在 Facebook 分享卡片的下方，建议控制在 150 字以内。', max_length=255, verbose_name='简短描述 (用于Facebook预览)')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='主图(封面)')),
                ('video_url', models.URLField(blank=True, help_text='如果你有视频，请填入YouTube链接，留空则不显示视频。', null=True, verbose_name='YouTube视频链接')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ceramics.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '陶瓷产品',
                'verbose_name_plural': '陶瓷产品',
                'ordering': ['-created_at'],
            },
        ),
    ]
